services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile

    volumes:
      - ./public:/var/www/project
      - ./config/php:/usr/local/etc/php/conf.d

    working_dir: /var/www/project

    environment:
      XDEBUG_MODE: debug
      PHP_IDE_CONFIG: serverName=WgManager

    extra_hosts:
      - "host.docker.internal:host-gateway"

    command: php-fpm

  nginx:
    image: nginx:latest

    ports:
      - 80:80
      - 443:443

    volumes:
      - ./public:/var/www/project
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - php