[Interface]
PrivateKey = sJW/bcS0qytilKKBg5D4rjEB++cGROy8fUYxoRqJ2Xw=
Address = 10.0.0.0/24
ListenPort = 51820

[Peer]
PublicKey = 9HEMLBgwC2YxqfD9CisnO8FwadA1bBGfx/+0DLSvfyM=
AllowedIPs = 10.0.0.4/32

[Peer]
PublicKey = hnr8PCWx7/VAYKDA9trfcbltCdIyjiqdvkba7egGhHk=
AllowedIPs = 10.0.0.5/32

[Peer]
PublicKey = H7HsG0PQ/4XOgj0ur2Z/k+UPTi95nYANzfUdgsJa3QM=
AllowedIPs = 10.0.0.2/32
