[Interface]
PrivateKey = oEoxj2bHSJQ2kAtnXHYfwazQwIMA2K1N/VqSMqdVpX4=
Address = 10.0.0.0/24
ListenPort = 51820

[Peer]
PublicKey = pT28pCjWOTZI8x9EYbSYO6hAIGMVZNkG8mr7dLcmpXM=
AllowedIPs = 10.0.0.2/32

[Peer]
PublicKey = VK+oi2t8x9KjQQs3XTjILXjkTnoO4aFMDmkVmy3h4m8=
AllowedIPs = 10.0.0.3/32

[Peer]
PublicKey = 9HEMLBgwC2YxqfD9CisnO8FwadA1bBGfx/+0DLSvfyM=
AllowedIPs = 10.0.0.4/32

[Peer]
PublicKey = hnr8PCWx7/VAYKDA9trfcbltCdIyjiqdvkba7egGhHk=
AllowedIPs = 10.0.0.5/32
