services:
  php:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: wgmanager-php

    restart: unless-stopped

    tty: true

    cap_add:
      - NET_ADMIN

    devices:
      - /dev/net/tun:/dev/net/tun

    working_dir: /var/www/project

    volumes:
      - .:/var/www/project

  nginx:
    image: nginx:1.28-alpine
    container_name: wgmanager-nginx
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - .:/var/www/project:ro
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro